
// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Enhances task instructions for clarity and ease of understanding, using task metadata.
 *
 * - enhanceTaskInstructions - A function that enhances the task instructions.
 * - EnhanceTaskInstructionsInput - The input type for the enhanceTaskInstructions function.
 * - EnhanceTaskInstructionsOutput - The return type for the enhanceTaskInstructions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceTaskInstructionsInputSchema = z.object({
  taskName: z.string().describe('The name of the exam task.'),
  taskDescription: z.string().describe('The description of the exam task.'),
  skillName: z.string().describe('The skill targeted by the exam task (e.g., Reading, Writing).'),
  levelName: z.string().describe('The CEFR level of the exam task (e.g., A1, B2, C1).'),
  exerciseTypeName: z.string().describe('The type of exercise (e.g., Multiple Choice, Gap Fill).'),
  designInstructions: z
    .string()
    .describe('The original design instructions for the task.'),
  difficultyInstructions: z
    .string()
    .describe('The original difficulty instructions for the task.'),
  difficultyCalibration: z
    .string()
    .describe('The original difficulty calibration text for the task.'),
});
export type EnhanceTaskInstructionsInput = z.infer<
  typeof EnhanceTaskInstructionsInputSchema
>;

const EnhanceTaskInstructionsOutputSchema = z.object({
  enhancedDesignInstructions: z
    .string()
    .describe('The enhanced design instructions for the task.'),
  enhancedDifficultyInstructions: z
    .string()
    .describe('The enhanced difficulty instructions for the task.'),
  enhancedDifficultyCalibration: z
    .string()
    .describe('The enhanced difficulty calibration text for the task.'),
});
export type EnhanceTaskInstructionsOutput = z.infer<
  typeof EnhanceTaskInstructionsOutputSchema
>;

export async function enhanceTaskInstructions(
  input: EnhanceTaskInstructionsInput
): Promise<EnhanceTaskInstructionsOutput> {
  return enhanceTaskInstructionsFlow(input);
}

const enhanceTaskInstructionsPrompt = ai.definePrompt({
  name: 'enhanceTaskInstructionsPrompt',
  input: {schema: EnhanceTaskInstructionsInputSchema},
  output: {schema: EnhanceTaskInstructionsOutputSchema},
  prompt: `You are an expert task instruction enhancer for language exams.
Your goal is to take potentially confusing or unclear instructions and make them as easy to understand as possible for the exam designer.
Consider the overall context of the task:
- Task Name: {{{taskName}}}
- Task Description: {{{taskDescription}}}
- Skill: {{{skillName}}}
- Level: {{{levelName}}}
- Exercise Type: {{{exerciseTypeName}}}

Now, review the following specific instruction sections:
- Original Design Instructions: {{{designInstructions}}}
- Original Difficulty Instructions: {{{difficultyInstructions}}}
- Original Difficulty Calibration: {{{difficultyCalibration}}}

Please provide enhanced versions of each of these three instruction sections (Design, Difficulty, Calibration).
Focus on clarity, conciseness, and ease of understanding.
When enhancing the instructions, particularly the 'Design Instructions', you can and should make use of parameters in curly braces where appropriate (e.g., {TOPIC}, {PERSON_NAME}, {MAX_WORDS}). These parameters will be replaced with dynamic values later.

Return the enhanced versions for each section.
  `,
});

const enhanceTaskInstructionsFlow = ai.defineFlow(
  {
    name: 'enhanceTaskInstructionsFlow',
    inputSchema: EnhanceTaskInstructionsInputSchema,
    outputSchema: EnhanceTaskInstructionsOutputSchema,
  },
  async input => {
    const {output} = await enhanceTaskInstructionsPrompt(input);
    return output!;
  }
);

